# This is a basic workflow to help you get started with Actions

name: Automated-Sitemap

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: npm install before excuting scripts
        run: npm install --no-optional
      - name: run scripts
        run: |
          chmod +x ./scripts/generate-sitemap.sh
          sh ./scripts/generate-sitemap.sh
        shell: bash
      - name: npm run build
        run: npm run build
